name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the Node.js version that matches your project

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build  # This now includes static export

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./out  # Directory with static files after build
          server-dir: /public_html/ui  # Root directory on your Hostinger account
          exclude: |
            **/.git*
            **/.DS_Store
            node_modules/**
            .github/**
            deploy.yml
